all :
	rm -rf test_program
	g++ -o test_program /home/asouari@actia.local/Desktop/lib_docan/Test/main.cpp /home/asouari@actia.local/Desktop/lib_docan/src/session.cpp /home/asouari@actia.local/Desktop/lib_docan/src/cantp.cpp
	./test_program
